## Preprocessing

In [2]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import tensorflow as tf

#  Import and read the charity_data.csv.
import pandas as pd
application_df = pd.read_csv("https://static.bc-edx.com/data/dl-1-2/m21/lms/starter/charity_data.csv")
application_df.head()

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [3]:
# Drop the non-beneficial ID columns, 'EIN' and 'NAME'.
application_df.drop(columns = ['EIN','NAME'], inplace=True)
application_df

,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1
...,...,...,...,...,...,...,...,...,...,...
34294,T4,Independent,C1000,ProductDev,Association,1,0,N,5000,0
34295,T4,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
34296,T3,CompanySponsored,C2000,Preservation,Association,1,0,N,5000,0
34297,T5,Independent,C3000,ProductDev,Association,1,0,N,5000,1
34298,T3,Independent,C1000,Preservation,Co-operative,1,1M-5M,N,36500179,0

In [4]:
# Determine the number of unique values in each column.
for i in application_df.columns:
    print(i, len(application_df[i].unique()))

APPLICATION_TYPE 17
AFFILIATION 6
CLASSIFICATION 71
USE_CASE 5
ORGANIZATION 4
STATUS 2
INCOME_AMT 9
SPECIAL_CONSIDERATIONS 2
ASK_AMT 8747
IS_SUCCESSFUL 2

In [5]:
# Look at APPLICATION_TYPE value counts for binning
application_counts = application_df['APPLICATION_TYPE'].value_counts()
application_counts

T3     27037
T4      1542
T6      1216
T5      1173
T19     1065
T8       737
T7       725
T10      528
T9       156
T13       66
T12       27
T2        16
T25        3
T14        3
T29        2
T15        2
T17        1
Name: APPLICATION_TYPE, dtype: int64

In [37]:
# Choose a cutoff value and create a list of application types to be replaced
# use the variable name `application_types_to_replace`
application_types_to_replace = list(application_counts[application_counts<500].index)

# Replace in dataframe
for app in application_types_to_replace:
    application_df['APPLICATION_TYPE'] = application_df['APPLICATION_TYPE'].replace(app,"Other")

# Check to make sure binning was successful
application_df['APPLICATION_TYPE'].value_counts()

T3       27037
T4        1542
T6        1216
T5        1173
T19       1065
Other      804
T8         737
T7         725
Name: APPLICATION_TYPE, dtype: int64

In [38]:
# Look at CLASSIFICATION value counts for binning
classification_counts = application_df['CLASSIFICATION'].value_counts()
classification_counts

C1000    17326
C2000     6074
C1200     4837
Other     2261
C3000     1918
C2100     1883
Name: CLASSIFICATION, dtype: int64

In [39]:
# You may find it helpful to look at CLASSIFICATION value counts >1
application_df['CLASSIFICATION'].value_counts().loc[lambda x : x >1]

C1000    17326
C2000     6074
C1200     4837
Other     2261
C3000     1918
C2100     1883
Name: CLASSIFICATION, dtype: int64

In [40]:
# Choose a cutoff value and create a list of classifications to be replaced
# use the variable name `classifications_to_replace`
classifications_to_replace = list(classification_counts[classification_counts<1000].index)

# Replace in dataframe
for cls in classifications_to_replace:
    application_df['CLASSIFICATION'] = application_df['CLASSIFICATION'].replace(cls,"Other")

# Check to make sure binning was successful
application_df['CLASSIFICATION'].value_counts()

C1000    17326
C2000     6074
C1200     4837
Other     2261
C3000     1918
C2100     1883
Name: CLASSIFICATION, dtype: int64

In [41]:
# Convert categorical data to numeric with `pd.get_dummies`
application_dummies = pd.get_dummies(application_df)
application_dummies.head()

,STATUS,ASK_AMT,IS_SUCCESSFUL,APPLICATION_TYPE_Other,APPLICATION_TYPE_T19,APPLICATION_TYPE_T3,APPLICATION_TYPE_T4,APPLICATION_TYPE_T5,APPLICATION_TYPE_T6,APPLICATION_TYPE_T7,...,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y
0,1,5000,1,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
1,1,108590,1,0,0,1,0,0,0,0,...,1,0,0,0,0,0,0,0,1,0
2,1,5000,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,1,0
3,1,6692,1,0,0,1,0,0,0,0,...,0,1,0,0,0,0,0,0,1,0
4,1,142590,1,0,0,1,0,0,0,0,...,0,0,1,0,0,0,0,0,1,0

In [42]:
# Split our preprocessed data into our features and target arrays
X = application_dummies.drop('IS_SUCCESSFUL', axis=1).values
y = application_dummies['IS_SUCCESSFUL'].values

# Split the preprocessed data into a training and testing dataset
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42, stratify=y)

In [43]:
# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

## Compile, Train and Evaluate the Model

In [55]:
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.
input_features = X_train_scaled.shape[1]
hidden_node1 = 128
hidden_node2 = 64
hidden_node3 = 32
nn = tf.keras.models.Sequential()

# First hidden layer
nn.add(tf.keras.layers.Dense(units=hidden_node1, activation='relu', input_dim=input_features))

# Second hidden layer
nn.add(tf.keras.layers.Dense(units=hidden_node2, activation='relu'))

# Third hidden layer
nn.add(tf.keras.layers.Dense(units=hidden_node3, activation='relu'))

# Output layer
nn.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

# Check the structure of the model
nn.summary()

Model: "sequential_5"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_16 (Dense)            (None, 128)               5504

 dense_17 (Dense)            (None, 64)                8256

 dense_18 (Dense)            (None, 32)                2080

 dense_19 (Dense)            (None, 1)                 33

=================================================================
Total params: 15873 (62.00 KB)
Trainable params: 15873 (62.00 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [56]:
# Compile the model
nn.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

In [57]:
# Train the model
fit_model = nn.fit(X_train_scaled, y_train, epochs=50)

Epoch 1/50
804/804 [==============================] - 2s 1ms/step - loss: 0.5691 - accuracy: 0.7228
Epoch 2/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5546 - accuracy: 0.7315
Epoch 3/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5512 - accuracy: 0.7331
Epoch 4/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5493 - accuracy: 0.7345
Epoch 5/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5483 - accuracy: 0.7340
Epoch 6/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5476 - accuracy: 0.7349
Epoch 7/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5466 - accuracy: 0.7357
Epoch 8/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5458 - accuracy: 0.7362
Epoch 9/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5454 - accuracy: 0.7358
Epoch 10/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5453 - accuracy: 0.7364
Epoch 11/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5447 - accuracy: 0.7367
Epoch 12/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5440 - accuracy: 0.7359
Epoch 13/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5439 - accuracy: 0.7370
Epoch 14/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5428 - accuracy: 0.7365
Epoch 15/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5429 - accuracy: 0.7368
Epoch 16/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5429 - accuracy: 0.7376
Epoch 17/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5417 - accuracy: 0.7378
Epoch 18/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5418 - accuracy: 0.7372
Epoch 19/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5413 - accuracy: 0.7380
Epoch 20/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5413 - accuracy: 0.7366
Epoch 21/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5413 - accuracy: 0.7380
Epoch 22/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5406 - accuracy: 0.7380
Epoch 23/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5404 - accuracy: 0.7389
Epoch 24/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5405 - accuracy: 0.7389
Epoch 25/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5399 - accuracy: 0.7388
Epoch 26/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5395 - accuracy: 0.7392
Epoch 27/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5392 - accuracy: 0.7388
Epoch 28/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5393 - accuracy: 0.7389
Epoch 29/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5392 - accuracy: 0.7374
Epoch 30/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5390 - accuracy: 0.7395
Epoch 31/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5386 - accuracy: 0.7386
Epoch 32/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5388 - accuracy: 0.7387
Epoch 33/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5381 - accuracy: 0.7391
Epoch 34/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5386 - accuracy: 0.7384
Epoch 35/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5378 - accuracy: 0.7399
Epoch 36/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5380 - accuracy: 0.7390
Epoch 37/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5376 - accuracy: 0.7395
Epoch 38/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5372 - accuracy: 0.7400
Epoch 39/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5369 - accuracy: 0.7397
Epoch 40/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5369 - accuracy: 0.7394
Epoch 41/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5368 - accuracy: 0.7401
Epoch 42/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5368 - accuracy: 0.7400
Epoch 43/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5369 - accuracy: 0.7402
Epoch 44/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5368 - accuracy: 0.7405
Epoch 45/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5358 - accuracy: 0.7401
Epoch 46/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5365 - accuracy: 0.7405
Epoch 47/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5364 - accuracy: 0.7400
Epoch 48/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5358 - accuracy: 0.7405
Epoch 49/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5356 - accuracy: 0.7405
Epoch 50/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5356 - accuracy: 0.7409

In [58]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 0s - loss: 0.5631 - accuracy: 0.7262 - 312ms/epoch - 1ms/step
Loss: 0.5631038546562195, Accuracy: 0.7261807322502136

In [ ]:
# Export our model to HDF5 file
#  YOUR CODE GOES HERE